-- Made with 'mini.colors' module of https://github.com/echasnovski/mini.nvim

if vim.g.colors_name ~= nil then
	vim.cmd("highlight clear")
end
vim.g.colors_name = "black-metal-gorgoroth"

local palette = {
	black = "#000000",
	deep_teal = "#5f8787",
	soft_brown = "#9b8d7f",
	muted_olive = "#8c7f70",
	gray = "#888888",
	light_gray = "#999999",
	pale_gray = "#aaaaaa",
	silver = "#c1c1c1",
	dark_gray = "#333333",
	charcoal = "#444444",
	slate_gray = "#505050",
	almost_black = "#252525",
	platinum = "#d4d4d4",
	ash_gray = "#bbbbbb",
	jet_black = "#121212",
	seafoam = "#689494",
	blush = "#f3a8a8",
	deep_charcoal = "#222222",
}

-- Highlight groups
local hi = vim.api.nvim_set_hl

hi(0, "@attribute", { fg = palette.muted_olive })
hi(0, "@boolean", { fg = palette.pale_gray })
hi(0, "@character", { fg = palette.deep_teal })
hi(0, "@character.special", { fg = palette.charcoal })
hi(0, "@class", { fg = palette.muted_olive })
hi(0, "@comment", { fg = palette.slate_gray, italic = true })
hi(0, "@conditional", { fg = palette.light_gray })
hi(0, "@constant", { fg = palette.pale_gray })
hi(0, "@constant.builtin", { fg = palette.pale_gray })
hi(0, "@constant.macro", { fg = palette.pale_gray })
hi(0, "@constructor", { fg = palette.gray })
hi(0, "@decorator", { fg = palette.deep_teal })
hi(0, "@enum", { fg = palette.muted_olive })
hi(0, "@enumMember", { fg = palette.pale_gray })
hi(0, "@error", { fg = palette.deep_teal })
hi(0, "@event", { fg = palette.deep_teal })
hi(0, "@exception", { fg = palette.deep_teal })
hi(0, "@field", { fg = palette.silver })
hi(0, "@float", { fg = palette.pale_gray })
hi(0, "@function", { fg = palette.gray })
hi(0, "@function.builtin", { fg = palette.gray, italic = true })
hi(0, "@function.call", { fg = palette.gray })
hi(0, "@function.macro", { fg = palette.deep_teal })
hi(0, "@include", { fg = palette.gray })
hi(0, "@interface", { fg = palette.light_gray })
hi(0, "@keyword", { fg = palette.light_gray })
hi(0, "@keyword.function", { fg = palette.light_gray })
hi(0, "@keyword.operator", { fg = palette.light_gray })
hi(0, "@keyword.return", { fg = palette.light_gray })
hi(0, "@label", { fg = palette.muted_olive })
hi(0, "@lsp.type.class", { fg = palette.light_gray })
hi(0, "@lsp.type.comment", { fg = palette.slate_gray })
hi(0, "@lsp.type.decorator", { fg = palette.gray })
hi(0, "@lsp.type.enum", { fg = palette.light_gray })
hi(0, "@lsp.type.enumMember", { fg = palette.pale_gray })
hi(0, "@lsp.type.function", { fg = palette.gray })
hi(0, "@lsp.type.interface", { fg = palette.light_gray })
hi(0, "@lsp.type.macro", { fg = palette.deep_teal })
hi(0, "@lsp.type.method", { fg = palette.gray })
hi(0, "@lsp.type.namespace", { fg = palette.light_gray })
hi(0, "@lsp.type.parameter", { fg = palette.deep_teal })
hi(0, "@lsp.type.property", { fg = palette.deep_teal })
hi(0, "@lsp.type.struct", { fg = palette.light_gray })
hi(0, "@lsp.type.type", { fg = palette.muted_olive })
hi(0, "@lsp.type.typeParameter", { fg = palette.muted_olive })
hi(0, "@method", { fg = palette.gray })
hi(0, "@method.call", { fg = palette.gray })
hi(0, "@modifier", { fg = palette.deep_teal })
hi(0, "@namespace", { fg = palette.deep_teal })
hi(0, "@neorg.anchors.declaration", { fg = palette.silver })
hi(0, "@neorg.anchors.declaration.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.anchors.definition.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.definitions.content", { fg = palette.pale_gray, italic = true })
hi(0, "@neorg.definitions.prefix", { fg = palette.charcoal })
hi(0, "@neorg.definitions.suffix", { fg = palette.charcoal })
hi(0, "@neorg.definitions.title", { bold = true })
hi(0, "@neorg.delimiters.horizontal_line", { fg = palette.charcoal })
hi(0, "@neorg.delimiters.strong", { fg = palette.charcoal })
hi(0, "@neorg.delimiters.weak", { fg = palette.charcoal })
hi(0, "@neorg.error", { fg = palette.deep_teal })
hi(0, "@neorg.footnotes.content", { fg = palette.pale_gray, italic = true })
hi(0, "@neorg.footnotes.prefix", { fg = palette.charcoal })
hi(0, "@neorg.footnotes.suffix", { fg = palette.charcoal })
hi(0, "@neorg.footnotes.title", { bold = true })
hi(0, "@neorg.headings.1.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.headings.1.title", { fg = palette.muted_olive })
hi(0, "@neorg.headings.2.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.headings.2.title", { fg = palette.muted_olive })
hi(0, "@neorg.headings.3.prefix", { fg = palette.pale_gray })
hi(0, "@neorg.headings.3.title", { fg = palette.pale_gray })
hi(0, "@neorg.headings.4.prefix", { fg = palette.soft_brown })
hi(0, "@neorg.headings.4.title", { fg = palette.soft_brown })
hi(0, "@neorg.headings.5.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.headings.5.title", { fg = palette.muted_olive })
hi(0, "@neorg.headings.6.prefix", { fg = palette.gray })
hi(0, "@neorg.headings.6.title", { fg = palette.gray })
hi(0, "@neorg.links.description", { fg = palette.pale_gray, underline = true })
hi(0, "@neorg.links.description.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.links.file", { fg = palette.dark_gray, italic = true })
hi(0, "@neorg.links.file.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.links.location.definition", { bold = true })
hi(0, "@neorg.links.location.definition.prefix", { fg = palette.charcoal })
hi(0, "@neorg.links.location.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.links.location.external_file", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.external_file.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.footnote", { bold = true })
hi(0, "@neorg.links.location.footnote.prefix", { fg = palette.charcoal })
hi(0, "@neorg.links.location.generic", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.generic.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.1", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.1.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.2", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.2.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.3", { fg = palette.pale_gray })
hi(0, "@neorg.links.location.heading.3.prefix", { fg = palette.pale_gray })
hi(0, "@neorg.links.location.heading.4", { fg = palette.soft_brown })
hi(0, "@neorg.links.location.heading.4.prefix", { fg = palette.soft_brown })
hi(0, "@neorg.links.location.heading.5", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.5.prefix", { fg = palette.muted_olive })
hi(0, "@neorg.links.location.heading.6", { fg = palette.gray })
hi(0, "@neorg.links.location.heading.6.prefix", { fg = palette.gray })
hi(0, "@neorg.links.location.marker", { link = "@neorg.markers.title" })
hi(0, "@neorg.links.location.marker.prefix", { link = "@neorg.markers.prefix" })
hi(0, "@neorg.links.location.url", { fg = palette.pale_gray, underline = true })
hi(0, "@neorg.lists.ordered.prefix", { fg = palette.light_gray })
hi(0, "@neorg.lists.unordered.prefix", { fg = palette.charcoal })
hi(0, "@neorg.markup.bold", { bold = true })
hi(0, "@neorg.markup.bold.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.free_form_delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.inline_comment", { fg = palette.slate_gray })
hi(0, "@neorg.markup.inline_comment.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.inline_math", { fg = palette.pale_gray })
hi(0, "@neorg.markup.inline_math.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.italic", { fg = palette.pale_gray, italic = true })
hi(0, "@neorg.markup.italic.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.spoiler", { fg = palette.deep_teal })
hi(0, "@neorg.markup.spoiler.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.strikethrough", { strikethrough = true })
hi(0, "@neorg.markup.strikethrough.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.subscript", { fg = palette.muted_olive })
hi(0, "@neorg.markup.subscript.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.superscript", { fg = palette.pale_gray })
hi(0, "@neorg.markup.superscript.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.underline", { underline = true })
hi(0, "@neorg.markup.underline.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.variable", { fg = palette.deep_teal })
hi(0, "@neorg.markup.variable.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.markup.verbatim", { fg = "#9a9a9a" })
hi(0, "@neorg.markup.verbatim.delimiter", { fg = palette.dark_gray })
hi(0, "@neorg.modifiers.escape", { fg = palette.muted_olive })
hi(0, "@neorg.modifiers.link", { fg = palette.dark_gray })
hi(0, "@neorg.quotes.1.content", { fg = palette.charcoal })
hi(0, "@neorg.quotes.1.prefix", { fg = palette.charcoal })
hi(0, "@neorg.quotes.2.content", { link = "Blue" })
hi(0, "@neorg.quotes.2.prefix", { link = "Blue" })
hi(0, "@neorg.quotes.3.content", { link = "Yellow" })
hi(0, "@neorg.quotes.3.prefix", { link = "Yellow" })
hi(0, "@neorg.quotes.4.content", { link = "Red" })
hi(0, "@neorg.quotes.4.prefix", { link = "Red" })
hi(0, "@neorg.quotes.5.content", { link = "Green" })
hi(0, "@neorg.quotes.5.prefix", { link = "Green" })
hi(0, "@neorg.quotes.6.content", { link = "Brown" })
hi(0, "@neorg.quotes.6.prefix", { link = "Brown" })
hi(0, "@neorg.selection_window.arrow", { fg = palette.silver })
hi(0, "@neorg.selection_window.heading", { link = "@annotation" })
hi(0, "@neorg.selection_window.key", { fg = palette.deep_teal })
hi(0, "@neorg.selection_window.keyname", { fg = palette.pale_gray })
hi(0, "@neorg.selection_window.nestedkeyname", { fg = palette.soft_brown })
hi(0, "@neorg.tags.carryover.begin", { fg = palette.muted_olive })
hi(0, "@neorg.tags.carryover.name", { fg = palette.silver })
hi(0, "@neorg.tags.carryover.name.delimiter", { fg = palette.silver })
hi(0, "@neorg.tags.carryover.name.word", { fg = palette.muted_olive })
hi(0, "@neorg.tags.carryover.parameters", { fg = palette.soft_brown })
hi(0, "@neorg.tags.comment.content", { fg = palette.slate_gray, italic = true })
hi(0, "@neorg.tags.ranged_verbatim.begin", { fg = palette.light_gray })
hi(0, "@neorg.tags.ranged_verbatim.code_block", { bg = palette.black })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.bracket", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.array.value", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.authors", { link = "@annotation" })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.categories", { fg = palette.light_gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.created", { fg = palette.pale_gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.description", { fg = palette.muted_olive })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.key", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.number", { fg = palette.pale_gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.object.bracket", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.title", { fg = palette.gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.trailing", { fg = palette.light_gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.updated", { fg = palette.pale_gray })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.value", { fg = palette.soft_brown })
hi(0, "@neorg.tags.ranged_verbatim.document_meta.version", { fg = palette.pale_gray })
hi(0, "@neorg.tags.ranged_verbatim.end", { fg = palette.light_gray })
hi(0, "@neorg.tags.ranged_verbatim.name", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.name.delimiter", { fg = palette.silver })
hi(0, "@neorg.tags.ranged_verbatim.name.word", { fg = palette.light_gray })
hi(0, "@neorg.tags.ranged_verbatim.parameters", { fg = palette.muted_olive })
hi(0, "@neorg.todo_items.cancelled", { fg = palette.dark_gray })
hi(0, "@neorg.todo_items.done", { fg = palette.soft_brown })
hi(0, "@neorg.todo_items.on_hold", { fg = palette.muted_olive })
hi(0, "@neorg.todo_items.pending", { fg = palette.deep_teal })
hi(0, "@neorg.todo_items.recurring", { fg = palette.light_gray })
hi(0, "@neorg.todo_items.uncertain", { fg = palette.pale_gray })
hi(0, "@neorg.todo_items.undone", { fg = palette.charcoal })
hi(0, "@neorg.todo_items.urgent", { fg = palette.deep_teal })
hi(0, "@none", { fg = palette.silver })
hi(0, "@number", { fg = palette.pale_gray })
hi(0, "@operator", { fg = palette.silver })
hi(0, "@parameter", { fg = palette.silver })
hi(0, "@property", { fg = palette.silver })
hi(0, "@punctuation.bracket", { fg = palette.silver })
hi(0, "@punctuation.delimiter", { fg = palette.charcoal })
hi(0, "@punctuation.special", { fg = palette.silver })
hi(0, "@regexp", { fg = palette.pale_gray })
hi(0, "@repeat", { fg = palette.light_gray })
hi(0, "@string", { fg = palette.soft_brown })
hi(0, "@string.escape", { fg = palette.pale_gray })
hi(0, "@string.regex", { fg = palette.pale_gray })
hi(0, "@string.special", { fg = palette.charcoal })
hi(0, "@struct", { fg = palette.muted_olive })
hi(0, "@symbol", { fg = palette.soft_brown })
hi(0, "@tag", { fg = palette.deep_teal })
hi(0, "@tag.attribute", { fg = palette.muted_olive })
hi(0, "@tag.delimiter", { fg = palette.charcoal })
hi(0, "@text", { fg = palette.silver })
hi(0, "@text.danger", { fg = palette.deep_teal })
hi(0, "@text.diff.add", { bg = palette.black, fg = palette.soft_brown })
hi(0, "@text.diff.delete", { bg = palette.black, fg = palette.deep_teal })
hi(0, "@text.emphasis", { fg = palette.pale_gray, italic = true })
hi(0, "@text.environment", { fg = palette.deep_teal })
hi(0, "@text.environment.name", { fg = palette.muted_olive })
hi(0, "@text.literal", { fg = palette.pale_gray })
hi(0, "@text.math", { fg = palette.pale_gray })
hi(0, "@text.note", { fg = palette.muted_olive })
hi(0, "@text.reference", { fg = palette.silver })
hi(0, "@text.strike", { fg = palette.black, strikethrough = true })
hi(0, "@text.strong", { bold = true })
hi(0, "@text.title", { fg = palette.gray })
hi(0, "@text.todo", { bg = palette.jet_black, fg = palette.muted_olive })
hi(0, "@text.underline", { fg = palette.black, underline = true })
hi(0, "@text.uri", { fg = palette.pale_gray, underline = true })
hi(0, "@text.warning", { fg = palette.light_gray })
hi(0, "@type", { fg = palette.muted_olive })
hi(0, "@type.builtin", { fg = palette.muted_olive, italic = true })
hi(0, "@type.definition", { fg = palette.muted_olive })
hi(0, "@type.qualifier", { fg = palette.light_gray })
hi(0, "@typeParameter", { fg = palette.muted_olive })
hi(0, "@variable", { fg = palette.deep_teal })
hi(0, "@variable.builtin", { fg = palette.deep_teal, italic = true })
hi(0, "Bold", { bold = true })
hi(0, "Boolean", { fg = palette.pale_gray })
hi(0, "BufferLineBackground", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineBuffer", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineBufferSelected", { bg = palette.black, bold = true, fg = palette.silver, italic = true })
hi(0, "BufferLineBufferVisible", { bg = palette.black, bold = true, fg = "#878787", italic = true })
hi(0, "BufferLineCloseButton", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineCloseButtonSelected", { bg = palette.black, fg = palette.silver })
hi(0, "BufferLineCloseButtonVisible", { bg = palette.black, fg = "#878787" })
hi(0, "BufferLineDevIconLua", { bg = palette.black, fg = "#366b8a" })
hi(0, "BufferLineDevIconLuaInactive", { bg = palette.black, fg = "#366b8a" })
hi(0, "BufferLineDevIconLuaSelected", { bg = palette.black, fg = "#366b8a" })
hi(0, "BufferLineDiagnostic", { bg = palette.black, fg = palette.almost_black })
hi(0, "BufferLineDiagnosticSelected", { bg = palette.black, bold = true, fg = "#909090", italic = true })
hi(0, "BufferLineDiagnosticVisible", { bg = palette.black, fg = palette.almost_black })
hi(0, "BufferLineDuplicate", { bg = palette.black, fg = palette.dark_gray, italic = true })
hi(0, "BufferLineDuplicateSelected", { bg = palette.black, fg = palette.dark_gray, italic = true })
hi(0, "BufferLineDuplicateVisible", { bg = palette.black, fg = palette.dark_gray, italic = true })
hi(0, "BufferLineError", { bg = palette.black, fg = palette.dark_gray, sp = palette.deep_teal })
hi(0, "BufferLineErrorDiagnostic", { bg = palette.black, fg = palette.almost_black, sp = "#476565" })
hi(
	0,
	"BufferLineErrorDiagnosticSelected",
	{ bg = palette.black, bold = true, fg = "#476565", italic = true, sp = "#476565" }
)
hi(0, "BufferLineErrorDiagnosticVisible", { bg = palette.black, fg = palette.almost_black })
hi(
	0,
	"BufferLineErrorSelected",
	{ bg = palette.black, bold = true, fg = palette.deep_teal, italic = true, sp = "#5f8787" }
)
hi(0, "BufferLineErrorVisible", { bg = palette.black, bold = true, fg = "#878787", italic = true })
hi(0, "BufferLineFill", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineGroupLabel", { bg = palette.dark_gray, fg = palette.black })
hi(0, "BufferLineGroupSeparator", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineHint", { bg = palette.black, fg = palette.dark_gray, sp = palette.pale_gray })
hi(0, "BufferLineHintDiagnostic", { bg = palette.black, fg = palette.almost_black, sp = "#7f7f7f" })
hi(
	0,
	"BufferLineHintDiagnosticSelected",
	{ bg = palette.black, bold = true, fg = "#7f7f7f", italic = true, sp = "#7f7f7f" }
)
hi(0, "BufferLineHintDiagnosticVisible", { bg = palette.black, fg = palette.almost_black })
hi(
	0,
	"BufferLineHintSelected",
	{ bg = palette.black, bold = true, fg = palette.pale_gray, italic = true, sp = palette.pale_gray }
)
hi(0, "BufferLineHintVisible", { bg = palette.black, bold = true, fg = "#878787", italic = true })
hi(0, "BufferLineIndicatorSelected", { bg = palette.black, fg = palette.jet_black })
hi(0, "BufferLineIndicatorVisible", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineInfo", { bg = palette.black, fg = palette.dark_gray, sp = palette.silver })
hi(0, "BufferLineInfoDiagnostic", { bg = palette.black, fg = palette.almost_black, sp = "#909090" })
hi(
	0,
	"BufferLineInfoDiagnosticSelected",
	{ bg = palette.black, bold = true, fg = "#909090", italic = true, sp = "#909090" }
)
hi(0, "BufferLineInfoDiagnosticVisible", { bg = palette.black, fg = palette.almost_black })
hi(
	0,
	"BufferLineInfoSelected",
	{ bg = palette.black, bold = true, fg = palette.silver, italic = true, sp = palette.silver }
)
hi(0, "BufferLineInfoVisible", { bg = palette.black, bold = true, fg = "#878787", italic = true })
hi(0, "BufferLineModified", { bg = palette.black, fg = palette.soft_brown })
hi(0, "BufferLineModifiedSelected", { bg = palette.black, fg = palette.soft_brown })
hi(0, "BufferLineModifiedVisible", { bg = palette.black, fg = palette.soft_brown })
hi(0, "BufferLineNumbers", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineNumbersSelected", { bg = palette.black, bold = true, fg = palette.silver, italic = true })
hi(0, "BufferLineNumbersVisible", { bg = palette.black, fg = "#878787" })
hi(0, "BufferLineOffsetSeparator", { bg = palette.black, fg = palette.silver })
hi(0, "BufferLinePick", { bg = palette.black, bold = true, fg = palette.deep_teal, italic = true })
hi(0, "BufferLinePickSelected", { bg = palette.black, bold = true, fg = palette.deep_teal, italic = true })
hi(0, "BufferLinePickVisible", { bg = palette.black, bold = true, fg = palette.deep_teal, italic = true })
hi(0, "BufferLineSeparator", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineSeparatorSelected", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineSeparatorVisible", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineTab", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineTabClose", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineTabSelected", { bg = palette.black, bold = true, fg = palette.jet_black })
hi(0, "BufferLineTabSeparator", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineTabSeparatorSelected", { bg = palette.black, fg = palette.black })
hi(0, "BufferLineTruncMarker", { bg = palette.black, fg = palette.dark_gray })
hi(0, "BufferLineWarning", { bg = palette.black, fg = palette.dark_gray, sp = palette.light_gray })
hi(0, "BufferLineWarningDiagnostic", { bg = palette.black, fg = palette.almost_black, sp = "#727272" })
hi(
	0,
	"BufferLineWarningDiagnosticSelected",
	{ bg = palette.black, bold = true, fg = "#727272", italic = true, sp = "#727272" }
)
hi(0, "BufferLineWarningDiagnosticVisible", { bg = palette.black, fg = palette.almost_black })
hi(
	0,
	"BufferLineWarningSelected",
	{ bg = palette.black, bold = true, fg = palette.light_gray, italic = true, sp = palette.light_gray }
)
hi(0, "BufferLineWarningVisible", { bg = palette.black, bold = true, fg = "#878787", italic = true })
hi(0, "Character", { fg = palette.deep_teal })
hi(0, "CmpDocumentation", { bg = palette.black, fg = palette.silver })
hi(0, "CmpDocumentationBorder", { bg = palette.black, fg = palette.silver })
hi(0, "CmpItemAbbr", { bg = palette.jet_black, fg = palette.silver })
hi(0, "CmpItemAbbrDefault", { fg = palette.silver })
hi(0, "CmpItemAbbrDeprecated", { fg = palette.dark_gray, strikethrough = true })
hi(0, "CmpItemAbbrDeprecatedDefault", { fg = palette.slate_gray })
hi(0, "CmpItemAbbrMatch", { fg = palette.gray })
hi(0, "CmpItemAbbrMatchDefault", { fg = palette.silver })
hi(0, "CmpItemAbbrMatchFuzzy", { fg = palette.gray })
hi(0, "CmpItemAbbrMatchFuzzyDefault", { fg = palette.silver })
hi(0, "CmpItemKindClass", { fg = palette.muted_olive })
hi(0, "CmpItemKindClassDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindColorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstant", { fg = palette.pale_gray })
hi(0, "CmpItemKindConstantDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindConstructor", { fg = palette.gray })
hi(0, "CmpItemKindConstructorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindDefault", { fg = palette.pale_gray })
hi(0, "CmpItemKindEnum", { fg = palette.muted_olive })
hi(0, "CmpItemKindEnumDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEnumMember", { fg = palette.muted_olive })
hi(0, "CmpItemKindEnumMemberDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindEvent", { fg = palette.muted_olive })
hi(0, "CmpItemKindEventDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindField", { fg = palette.deep_teal })
hi(0, "CmpItemKindFieldDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFileDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFolderDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindFunction", { fg = palette.gray })
hi(0, "CmpItemKindFunctionDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindInterface", { fg = palette.muted_olive })
hi(0, "CmpItemKindInterfaceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindKeyword", { fg = palette.light_gray })
hi(0, "CmpItemKindKeywordDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindMethod", { fg = palette.gray })
hi(0, "CmpItemKindMethodDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindModule", { fg = palette.silver })
hi(0, "CmpItemKindModuleDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindOperator", { fg = palette.silver })
hi(0, "CmpItemKindOperatorDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindProperty", { fg = palette.deep_teal })
hi(0, "CmpItemKindPropertyDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindReference", { fg = palette.deep_teal })
hi(0, "CmpItemKindReferenceDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindSnippet", { fg = palette.light_gray })
hi(0, "CmpItemKindSnippetDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindStruct", { fg = palette.muted_olive })
hi(0, "CmpItemKindStructDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTextDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindTypeParameter", { fg = palette.muted_olive })
hi(0, "CmpItemKindTypeParameterDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindUnit", { fg = palette.muted_olive })
hi(0, "CmpItemKindUnitDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindValue", { fg = palette.pale_gray })
hi(0, "CmpItemKindValueDefault", { link = "CmpItemKind" })
hi(0, "CmpItemKindVariable", { fg = palette.deep_teal })
hi(0, "CmpItemKindVariableDefault", { link = "CmpItemKind" })
hi(0, "CmpItemMenu", { fg = palette.light_gray })
hi(0, "CmpItemMenuDefault", { fg = palette.silver })
hi(0, "ColorColumn", { bg = palette.jet_black })
hi(0, "Comment", { fg = palette.slate_gray })
hi(0, "Conceal", { bg = palette.black, fg = palette.gray })
hi(0, "Conditional", { fg = palette.light_gray })
hi(0, "Constant", { fg = palette.pale_gray })
hi(0, "Cursor", { bg = palette.silver, fg = palette.black })
hi(0, "CursorColumn", { bg = palette.jet_black })
hi(0, "CursorLine", { bg = palette.jet_black })
hi(0, "CursorLineNr", { bg = palette.jet_black, fg = palette.light_gray })
hi(0, "Debug", { fg = palette.deep_teal })
hi(0, "Define", { fg = palette.light_gray })
hi(0, "Delimiter", { fg = palette.charcoal })
hi(0, "DiagnosticError", { fg = palette.deep_teal })
hi(0, "DiagnosticHint", { fg = palette.pale_gray })
hi(0, "DiagnosticInfo", { fg = palette.silver })
hi(0, "DiagnosticUnderlineError", { sp = palette.deep_teal, undercurl = true })
hi(0, "DiagnosticUnderlineHint", { sp = palette.pale_gray, undercurl = true })
hi(0, "DiagnosticUnderlineInformation", { sp = palette.charcoal, undercurl = true })
hi(0, "DiagnosticUnderlineWarn", { sp = palette.light_gray, undercurl = true })
hi(0, "DiagnosticUnderlineWarning", { sp = palette.light_gray, undercurl = true })
hi(0, "DiagnosticWarn", { fg = palette.light_gray })
hi(0, "DiffAdd", { bg = palette.black, fg = palette.soft_brown })
hi(0, "DiffAdded", { bg = palette.black, fg = palette.soft_brown })
hi(0, "DiffChange", { bg = palette.black, fg = palette.dark_gray })
hi(0, "DiffDelete", { bg = palette.black, fg = palette.deep_teal })
hi(0, "DiffFile", { bg = palette.black, fg = palette.deep_teal })
hi(0, "DiffLine", { bg = palette.black, fg = palette.gray })
hi(0, "DiffNewFile", { bg = palette.black, fg = palette.soft_brown })
hi(0, "DiffRemoved", { bg = palette.black, fg = palette.deep_teal })
hi(0, "DiffText", { bg = palette.black, fg = palette.gray })
hi(0, "Directory", { fg = palette.gray })
hi(0, "DressingSelectIdx", { fg = palette.pale_gray })
hi(0, "Error", { bg = palette.black, fg = palette.deep_teal })
hi(0, "ErrorMsg", { bg = palette.black, fg = palette.deep_teal })
hi(0, "Exception", { fg = palette.deep_teal })
hi(0, "Float", { fg = palette.pale_gray })
hi(0, "FloatBorder", { bg = palette.black, fg = palette.silver })
hi(0, "FoldColumn", { bg = palette.black, fg = palette.pale_gray })
hi(0, "Folded", { bg = palette.jet_black, fg = palette.dark_gray })
hi(0, "Function", { fg = palette.gray })
hi(0, "GitGutterAdd", { bg = palette.black, fg = palette.soft_brown })
hi(0, "GitGutterChange", { bg = palette.black, fg = palette.gray })
hi(0, "GitGutterChangeDelete", { bg = palette.black, fg = palette.light_gray })
hi(0, "GitGutterDelete", { bg = palette.black, fg = palette.deep_teal })
hi(0, "GitSignsStagedAdd", { bg = palette.black, fg = "#6e4c4c" })
hi(0, "GitSignsStagedAddLn", { bg = palette.black, fg = "#6e4c4c" })
hi(0, "GitSignsStagedAddNr", { bg = palette.black, fg = "#6e4c4c" })
hi(0, "GitSignsStagedChange", { bg = palette.black, fg = palette.charcoal })
hi(0, "GitSignsStagedChangeLn", { bg = palette.black, fg = "#191919" })
hi(0, "GitSignsStagedChangeNr", { bg = palette.black, fg = palette.charcoal })
hi(0, "GitSignsStagedChangedelete", { bg = palette.black, fg = palette.charcoal })
hi(0, "GitSignsStagedChangedeleteLn", { bg = palette.black, fg = "#191919" })
hi(0, "GitSignsStagedChangedeleteNr", { bg = palette.black, fg = palette.charcoal })
hi(0, "GitSignsStagedDelete", { bg = palette.black, fg = "#2f4343" })
hi(0, "GitSignsStagedDeleteNr", { bg = palette.black, fg = "#2f4343" })
hi(0, "GitSignsStagedTopdelete", { bg = palette.black, fg = "#2f4343" })
hi(0, "GitSignsStagedTopdeleteNr", { bg = palette.black, fg = "#2f4343" })
hi(0, "IblIndent", { fg = palette.deep_charcoal, nocombine = true })
hi(0, "IblScope", { fg = palette.light_gray, nocombine = true })
hi(0, "IblWhitespace", { link = "Whitespace" })
hi(0, "Identifier", { fg = palette.deep_teal })
hi(0, "IlluminatedWordRead", { sp = palette.light_gray, underline = true })
hi(0, "IlluminatedWordText", { sp = palette.light_gray, underline = true })
hi(0, "IlluminatedWordWrite", { sp = palette.light_gray, underline = true })
hi(0, "IncSearch", { bg = palette.pale_gray, fg = palette.jet_black })
hi(0, "Include", { fg = palette.gray })
hi(0, "IndentBlanklineChar", { fg = palette.deep_charcoal, nocombine = true })
hi(0, "IndentBlanklineContextChar", { fg = palette.light_gray, nocombine = true })
hi(0, "Keyword", { fg = palette.light_gray })
hi(0, "Label", { fg = palette.muted_olive })
hi(0, "LineNr", { bg = palette.black, fg = palette.light_gray })
hi(0, "LspDiagnosticsDefaultError", { fg = palette.deep_teal })
hi(0, "LspDiagnosticsDefaultHint", { fg = palette.pale_gray })
hi(0, "LspDiagnosticsDefaultInformation", { fg = palette.silver })
hi(0, "LspDiagnosticsDefaultWarning", { fg = palette.light_gray })
hi(0, "LspDiagnosticsUnderlineError", { sp = palette.deep_teal, undercurl = true })
hi(0, "LspDiagnosticsUnderlineHint", { sp = palette.pale_gray, undercurl = true })
hi(0, "LspDiagnosticsUnderlineInformation", { sp = palette.charcoal, undercurl = true })
hi(0, "LspDiagnosticsUnderlineWarning", { sp = palette.light_gray, undercurl = true })
hi(0, "LspInlayHint", { fg = palette.dark_gray, italic = true })
hi(0, "LspReferenceRead", { sp = palette.light_gray, underline = true })
hi(0, "LspReferenceText", { sp = palette.light_gray, underline = true })
hi(0, "LspReferenceWrite", { sp = palette.light_gray, underline = true })
hi(0, "Macro", { fg = palette.deep_teal })
hi(0, "MatchParen", { bg = palette.dark_gray })
hi(0, "MiniCompletionActiveParameter", { bg = palette.jet_black })
hi(0, "ModeMsg", { fg = palette.soft_brown })
hi(0, "MoreMsg", { fg = palette.soft_brown })

-- neotest
hi(0, "NeotestAdapterName", { ctermfg = 9, fg = palette.blush })
hi(0, "NeotestDir", { ctermfg = 14, fg = palette.seafoam })
hi(0, "NeotestExpandMarker", { ctermfg = 248, fg = palette.seafoam })
hi(0, "NeotestFailed", { ctermfg = 9, fg = palette.blush })
hi(0, "NeotestFile", { ctermfg = 14, fg = palette.seafoam })
hi(0, "NeotestFocused", { bold = true, underline = true })
hi(0, "NeotestIndent", { ctermfg = 248, fg = palette.gray })
hi(0, "NeotestMarked", { bold = true, ctermfg = 130, fg = palette.blush })
hi(0, "NeotestNamespace", { ctermfg = 13, fg = palette.platinum })
hi(0, "NeotestPassed", { ctermfg = 10, fg = palette.seafoam })
hi(0, "NeotestRunning", { ctermfg = 11, fg = palette.platinum })
hi(0, "NeotestSkipped", { ctermfg = 14, fg = palette.seafoam })
hi(0, "NeotestTarget", { ctermfg = 9, fg = palette.blush })
hi(0, "NeotestWatching", { ctermfg = 11, fg = palette.platinum })
hi(0, "NeotestWinSelect", { bold = true, ctermfg = 14, fg = palette.seafoam })
--

hi(0, "NoiceFormatProgressDone", { bg = palette.muted_olive, fg = palette.jet_black })
hi(0, "NoiceHiddenCursor", { blend = 100, nocombine = true })
hi(0, "NonText", { fg = palette.dark_gray })
hi(0, "Normal", { bg = palette.black, fg = palette.silver })
hi(0, "NormalFloat", { bg = palette.black, fg = palette.silver })
hi(0, "NormalNC", { bg = palette.black, fg = palette.silver })
hi(0, "NotifyDEBUGBorder", { fg = palette.pale_gray })
hi(0, "NotifyDEBUGIcon", { fg = palette.pale_gray })
hi(0, "NotifyDEBUGTitle", { fg = palette.pale_gray })
hi(0, "NotifyERRORBorder", { fg = palette.deep_teal })
hi(0, "NotifyERRORIcon", { fg = palette.deep_teal })
hi(0, "NotifyERRORTitle", { fg = palette.deep_teal })
hi(0, "NotifyINFOBody219", { link = "NotifyINFOBody" })
hi(0, "NotifyINFOBorder", { fg = palette.silver })
hi(0, "NotifyINFOBorder219", { fg = palette.silver })
hi(0, "NotifyINFOIcon", { fg = palette.silver })
hi(0, "NotifyINFOIcon219", { fg = palette.silver })
hi(0, "NotifyINFOTitle", { fg = palette.silver })
hi(0, "NotifyINFOTitle219", { fg = palette.silver })
hi(0, "NotifyTRACEBorder", { fg = palette.pale_gray })
hi(0, "NotifyTRACEIcon", { fg = palette.pale_gray })
hi(0, "NotifyTRACETitle", { fg = palette.pale_gray })
hi(0, "NotifyWARNBorder", { fg = palette.light_gray })
hi(0, "NotifyWARNIcon", { fg = palette.light_gray })
hi(0, "NotifyWARNTitle", { fg = palette.light_gray })
hi(0, "Number", { fg = palette.pale_gray })
hi(0, "NvimInternalError", { bg = palette.deep_teal, fg = palette.black })
hi(0, "Operator", { fg = palette.light_gray })
hi(0, "Pmenu", { bg = palette.jet_black, fg = palette.silver })
hi(0, "PmenuSel", { bg = palette.silver, fg = palette.jet_black })
hi(0, "PreProc", { fg = palette.muted_olive })
hi(0, "Question", { fg = palette.gray })
hi(0, "QuickFixLine", { bg = palette.jet_black })
hi(0, "Repeat", { fg = palette.muted_olive })
hi(0, "Search", { bg = palette.muted_olive, fg = palette.jet_black })
hi(0, "SignColumn", { bg = palette.black, fg = palette.light_gray })
hi(0, "Special", { fg = palette.pale_gray })
hi(0, "SpecialChar", { fg = palette.charcoal })
hi(0, "SpecialKey", { fg = palette.dark_gray })
hi(0, "SpellBad", { sp = palette.deep_teal, undercurl = true })
hi(0, "SpellCap", { sp = palette.gray, undercurl = true })
hi(0, "SpellLocal", { sp = palette.pale_gray, undercurl = true })
hi(0, "SpellRare", { sp = palette.light_gray, undercurl = true })
hi(0, "Statement", { fg = palette.deep_teal })
hi(0, "StatusLine", { bg = palette.deep_charcoal, fg = palette.silver })
hi(0, "StatusLineNC", { bg = palette.jet_black, fg = palette.light_gray })
hi(0, "StorageClass", { fg = palette.muted_olive })
hi(0, "String", { fg = palette.soft_brown })
hi(0, "Structure", { fg = palette.light_gray })
hi(0, "Substitute", { bg = palette.muted_olive, fg = palette.jet_black })
hi(0, "TSAnnotation", { fg = palette.charcoal })
hi(0, "TSAttribute", { fg = palette.muted_olive })
hi(0, "TSBoolean", { fg = palette.pale_gray })
hi(0, "TSCharacter", { fg = palette.deep_teal })
hi(0, "TSComment", { fg = palette.slate_gray, italic = true })
hi(0, "TSConditional", { fg = palette.light_gray })
hi(0, "TSConstBuiltin", { fg = palette.pale_gray, italic = true })
hi(0, "TSConstMacro", { fg = palette.deep_teal })
hi(0, "TSConstant", { fg = palette.pale_gray })
hi(0, "TSConstructor", { fg = palette.gray })
hi(0, "TSCurrentScope", { bold = true })
hi(0, "TSDefinition", { sp = palette.light_gray, underline = true })
hi(0, "TSDefinitionUsage", { sp = palette.light_gray, underline = true })
hi(0, "TSEmphasis", { fg = palette.pale_gray, italic = true })
hi(0, "TSError", { fg = palette.deep_teal })
hi(0, "TSException", { fg = palette.deep_teal })
hi(0, "TSField", { fg = palette.silver })
hi(0, "TSFloat", { fg = palette.pale_gray })
hi(0, "TSFuncBuiltin", { fg = palette.gray, italic = true })
hi(0, "TSFuncMacro", { fg = palette.deep_teal })
hi(0, "TSFunction", { fg = palette.gray })
hi(0, "TSInclude", { fg = palette.gray })
hi(0, "TSKeyword", { fg = palette.light_gray })
hi(0, "TSKeywordFunction", { fg = palette.light_gray })
hi(0, "TSKeywordOperator", { fg = palette.light_gray })
hi(0, "TSLabel", { fg = palette.muted_olive })
hi(0, "TSLiteral", { fg = palette.pale_gray })
hi(0, "TSMethod", { fg = palette.gray })
hi(0, "TSNamespace", { fg = palette.deep_teal })
hi(0, "TSNodeKey", { reverse = true })
hi(0, "TSNone", { fg = palette.silver })
hi(0, "TSNumber", { fg = palette.pale_gray })
hi(0, "TSOperator", { fg = palette.silver })
hi(0, "TSParameter", { fg = palette.silver })
hi(0, "TSParameterReference", { fg = palette.silver })
hi(0, "TSProperty", { fg = palette.silver })
hi(0, "TSPunctBracket", { fg = palette.silver })
hi(0, "TSPunctDelimiter", { fg = palette.charcoal })
hi(0, "TSPunctSpecial", { fg = palette.silver })
hi(0, "TSRepeat", { fg = palette.light_gray })
hi(0, "TSStrike", { fg = palette.black, strikethrough = true })
hi(0, "TSString", { fg = palette.soft_brown })
hi(0, "TSStringEscape", { fg = palette.pale_gray })
hi(0, "TSStringRegex", { fg = palette.pale_gray })
hi(0, "TSStrong", { bold = true })
hi(0, "TSSymbol", { fg = palette.soft_brown })
hi(0, "TSTag", { fg = palette.deep_teal })
hi(0, "TSTagDelimiter", { fg = palette.charcoal })
hi(0, "TSText", { fg = palette.silver })
hi(0, "TSTitle", { fg = palette.gray })
hi(0, "TSType", { fg = palette.muted_olive })
hi(0, "TSTypeBuiltin", { fg = palette.muted_olive, italic = true })
hi(0, "TSURI", { fg = palette.pale_gray, underline = true })
hi(0, "TSUnderline", { fg = palette.black, underline = true })
hi(0, "TSVariable", { fg = palette.deep_teal })
hi(0, "TSVariableBuiltin", { fg = palette.deep_teal, italic = true })
hi(0, "TabLine", { bg = palette.jet_black, fg = palette.dark_gray })
hi(0, "TabLineFill", { bg = palette.jet_black, fg = palette.dark_gray })
hi(0, "TabLineSel", { bg = palette.jet_black, fg = palette.soft_brown })
hi(0, "Tag", { fg = palette.muted_olive })
hi(0, "TelescopeBorder", { bg = palette.black, fg = palette.black })
hi(0, "TelescopeNormal", { bg = palette.black })
hi(0, "TelescopePreviewLine", { bg = palette.jet_black })
hi(0, "TelescopePreviewTitle", { bg = palette.soft_brown, fg = palette.jet_black })
hi(0, "TelescopePromptBorder", { bg = palette.deep_charcoal, fg = palette.deep_charcoal })
hi(0, "TelescopePromptNormal", { bg = palette.deep_charcoal, fg = palette.silver })
hi(0, "TelescopePromptPrefix", { bg = palette.deep_charcoal, fg = palette.deep_teal })
hi(0, "TelescopePromptTitle", { bg = palette.deep_teal, fg = palette.jet_black })
hi(0, "TelescopeResultsTitle", { bg = palette.black, fg = palette.black })
hi(0, "TelescopeSelection", { bg = palette.deep_charcoal })
hi(0, "TermCursor", { bg = palette.silver, fg = palette.black })
hi(0, "TermCursorNC", { bg = palette.silver, fg = palette.black })
hi(0, "Title", { fg = palette.gray })
hi(0, "Todo", { bg = palette.jet_black, fg = palette.muted_olive })
hi(0, "TodoBgFIX", { bg = palette.deep_teal, bold = true, fg = palette.silver })
hi(0, "TodoBgHACK", { bg = palette.light_gray, bold = true, fg = palette.black })
hi(0, "TodoBgNOTE", { bg = palette.pale_gray, bold = true, fg = palette.black })
hi(0, "TodoBgPERF", { bg = palette.deep_teal, bold = true, fg = palette.silver })
hi(0, "TodoBgTEST", { bg = palette.deep_teal, bold = true, fg = palette.silver })
hi(0, "TodoBgTODO", { bg = palette.silver, bold = true, fg = palette.black })
hi(0, "TodoBgWARN", { bg = palette.light_gray, bold = true, fg = palette.black })
hi(0, "TodoFgFIX", { fg = palette.deep_teal })
hi(0, "TodoFgHACK", { fg = palette.light_gray })
hi(0, "TodoFgNOTE", { fg = palette.pale_gray })
hi(0, "TodoFgPERF", { fg = palette.deep_teal })
hi(0, "TodoFgTEST", { fg = palette.deep_teal })
hi(0, "TodoFgTODO", { fg = palette.silver })
hi(0, "TodoFgWARN", { fg = palette.light_gray })
hi(0, "TodoSignFIX", { bg = palette.black, fg = palette.deep_teal })
hi(0, "TodoSignHACK", { bg = palette.black, fg = palette.light_gray })
hi(0, "TodoSignNOTE", { bg = palette.black, fg = palette.pale_gray })
hi(0, "TodoSignPERF", { bg = palette.black, fg = palette.deep_teal })
hi(0, "TodoSignTEST", { bg = palette.black, fg = palette.deep_teal })
hi(0, "TodoSignTODO", { bg = palette.black, fg = palette.silver })
hi(0, "TodoSignWARN", { bg = palette.black, fg = palette.light_gray })
hi(0, "TooLong", { fg = palette.deep_teal })
hi(0, "TreesitterContext", { bg = palette.jet_black, italic = true })
hi(0, "Type", { fg = palette.muted_olive })
hi(0, "Typedef", { fg = palette.muted_olive })
hi(0, "UfoFoldedBg", { bg = palette.jet_black })
hi(0, "UfoFoldedFg", { fg = palette.silver })
hi(0, "Underlined", { fg = palette.deep_teal })
hi(0, "User1", { bg = palette.deep_charcoal, fg = palette.deep_teal })
hi(0, "User2", { bg = palette.deep_charcoal, fg = palette.light_gray })
hi(0, "User3", { bg = palette.deep_charcoal, fg = palette.silver })
hi(0, "User4", { bg = palette.deep_charcoal, fg = palette.pale_gray })
hi(0, "User5", { bg = palette.deep_charcoal, fg = palette.silver })
hi(0, "User6", { bg = palette.jet_black, fg = palette.silver })
hi(0, "User7", { bg = palette.deep_charcoal, fg = palette.silver })
hi(0, "User8", { bg = palette.deep_charcoal, fg = palette.black })
hi(0, "User9", { bg = palette.deep_charcoal, fg = palette.black })
hi(0, "VertSplit", { bg = palette.black, fg = palette.silver })
hi(0, "Visual", { bg = palette.deep_charcoal })
hi(0, "VisualNOS", { fg = palette.deep_teal })
hi(0, "WarningMsg", { fg = palette.deep_teal })
hi(0, "WildMenu", { bg = palette.muted_olive, fg = palette.deep_teal })
hi(0, "WinBar", { fg = palette.silver })
hi(0, "WinBarNC", { fg = palette.light_gray })
hi(0, "gitcommitBranch", { bold = true, fg = palette.pale_gray })
hi(0, "gitcommitComment", { fg = palette.slate_gray })
hi(0, "gitcommitDiscarded", { fg = palette.dark_gray })
hi(0, "gitcommitDiscardedFile", { bold = true, fg = palette.deep_teal })
hi(0, "gitcommitDiscardedType", { fg = palette.gray })
hi(0, "gitcommitHeader", { fg = palette.light_gray })
hi(0, "gitcommitOverflow", { fg = palette.deep_teal })
hi(0, "gitcommitSelected", { fg = palette.dark_gray })
hi(0, "gitcommitSelectedFile", { bold = true, fg = palette.soft_brown })
hi(0, "gitcommitSelectedType", { fg = palette.gray })
hi(0, "gitcommitSummary", { fg = palette.soft_brown })
hi(0, "gitcommitUnmergedFile", { bold = true, fg = palette.deep_teal })
hi(0, "gitcommitUnmergedType", { fg = palette.gray })
hi(0, "gitcommitUntracked", { fg = palette.dark_gray })
hi(0, "gitcommitUntrackedFile", { fg = palette.muted_olive })
hi(0, "lCursor", { bg = palette.silver, fg = palette.black })
hi(0, "lualine_a_command", { bg = palette.seafoam, bold = true, fg = palette.black })
hi(0, "lualine_a_inactive", { bg = palette.platinum, bold = true, fg = palette.black })
hi(0, "lualine_a_insert", { bg = palette.blush, bold = true, fg = palette.black })
hi(0, "lualine_a_normal", { bg = palette.platinum, bold = true, fg = palette.black })
hi(0, "lualine_a_replace", { bg = palette.ash_gray, bold = true, fg = palette.black })
hi(0, "lualine_a_terminal", { bg = palette.seafoam, bold = true, fg = palette.black })
hi(0, "lualine_a_visual", { bg = palette.ash_gray, bold = true, fg = palette.black })
hi(0, "lualine_b_command", { bg = palette.black, fg = palette.seafoam })
hi(0, "lualine_b_inactive", { bg = palette.black, fg = palette.platinum })
hi(0, "lualine_b_insert", { bg = palette.black, fg = palette.blush })
hi(0, "lualine_b_normal", { bg = palette.black, fg = palette.platinum })
hi(0, "lualine_b_replace", { bg = palette.black, fg = palette.ash_gray })
hi(0, "lualine_b_terminal", { bg = palette.black, fg = palette.seafoam })
hi(0, "lualine_b_visual", { bg = palette.black, fg = palette.ash_gray })
hi(0, "lualine_c_command", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_diagnostics_error_command", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_inactive", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_insert", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_normal", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_replace", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_terminal", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_error_visual", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_c_diagnostics_hint_command", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_inactive", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_insert", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_normal", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_replace", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_terminal", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_hint_visual", { bg = palette.almost_black, fg = palette.pale_gray })
hi(0, "lualine_c_diagnostics_info_command", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_inactive", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_insert", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_normal", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_replace", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_terminal", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_info_visual", { bg = palette.almost_black, fg = palette.silver })
hi(0, "lualine_c_diagnostics_warn_command", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_inactive", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_insert", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_normal", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_replace", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_terminal", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_diagnostics_warn_visual", { bg = palette.almost_black, fg = palette.light_gray })
hi(0, "lualine_c_inactive", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_insert", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_normal", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_replace", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_terminal", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_c_visual", { bg = palette.almost_black, fg = palette.platinum })
hi(0, "lualine_transitional_lualine_a_command_to_lualine_b_command", { bg = palette.deep_charcoal, fg = palette.gray })
hi(
	0,
	"lualine_transitional_lualine_a_insert_to_lualine_b_insert",
	{ bg = palette.deep_charcoal, fg = palette.platinum }
)
hi(0, "lualine_transitional_lualine_a_normal_to_lualine_b_normal", { bg = palette.deep_charcoal, fg = palette.gray })
hi(
	0,
	"lualine_transitional_lualine_b_command_to_lualine_c_command",
	{ bg = palette.jet_black, fg = palette.deep_charcoal }
)
hi(
	0,
	"lualine_transitional_lualine_b_insert_to_lualine_c_normal",
	{ bg = palette.jet_black, fg = palette.deep_charcoal }
)
hi(
	0,
	"lualine_transitional_lualine_b_normal_to_lualine_c_normal",
	{ bg = palette.jet_black, fg = palette.deep_charcoal }
)
hi(0, "lualine_x_diff_added_command", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_inactive", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_insert", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_normal", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_replace", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_terminal", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_added_visual", { bg = palette.almost_black, fg = palette.soft_brown })
hi(0, "lualine_x_diff_modified_command", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_inactive", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_insert", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_normal", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_replace", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_terminal", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_modified_visual", { bg = palette.almost_black, fg = palette.gray })
hi(0, "lualine_x_diff_removed_command", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_inactive", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_insert", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_normal", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_replace", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_terminal", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "lualine_x_diff_removed_visual", { bg = palette.almost_black, fg = palette.deep_teal })
hi(0, "rainbowcol1", { fg = palette.light_gray })
hi(0, "rainbowcol2", { fg = palette.pale_gray })
hi(0, "rainbowcol3", { fg = palette.muted_olive })
hi(0, "rainbowcol4", { fg = palette.silver })
hi(0, "rainbowcol5", { fg = palette.pale_gray })
hi(0, "rainbowcol6", { fg = palette.gray })
hi(0, "rainbowcol7", { fg = palette.light_gray })

-- Terminal colors
local g = vim.g

g.terminal_color_0 = palette.black
g.terminal_color_1 = palette.deep_teal
g.terminal_color_2 = palette.soft_brown
g.terminal_color_3 = palette.muted_olive
g.terminal_color_4 = palette.gray
g.terminal_color_5 = palette.light_gray
g.terminal_color_6 = palette.pale_gray
g.terminal_color_7 = palette.silver
g.terminal_color_8 = palette.dark_gray
g.terminal_color_9 = palette.deep_teal
g.terminal_color_10 = palette.soft_brown
g.terminal_color_11 = palette.muted_olive
g.terminal_color_12 = palette.gray
g.terminal_color_13 = palette.light_gray
g.terminal_color_14 = palette.pale_gray
g.terminal_color_15 = palette.silver
