# name: MAYHEM colors for Herdr
# url: https://github.com/herd
# upstream: https://github.com/metalelf0/black-metal.nvim/raw/main/extras/herdr/mayhem.toml
# author: Andrea Schiavini (original code by Casey Miller)

[theme]
background = "#000000"
foreground = "#c1c1c1"
alternate_background = "#4d2020"
alternate_foreground = "#5f8787"
comment = "#505050"
visual_selection = "#222222"
line_highlight = "#000000"

[colors]
black = "#4d2020"
grey = "#505050"
red = "#5f8787"
orange = "#aaaaaa"
green = "#c1c1c1"
yellow = "#888888"
blue = "#aaaaaa"
purple = "#999999"
magenta = "#eecc6c"
cyan = "#f3ecd4"
white = "#c1c1c1"

[palette]
string = "#f3ecd4"
number = "#aaaaaa"
keyword = "#999999"
function = "#888888"
type = "#eecc6c"
constant = "#aaaaaa"
operator = "#9b99a3"
property = "#c1c1c1"
